version: '3'

services:
  # app:
  #   build: .
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   command: npm run start:dev
  #   ports:
  #     - '3000:3000'

  loki:
    image: grafana/loki:latest
    ports:
      - '3101:3100'
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./docker/promtail-config.yaml:/etc/promtail/config.yml
      - ./logs:/app/logs
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana
    ports:
      - '3001:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_PUBLIC_DASHBOARDS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    depends_on:
      - loki

  redis:
    image: redis
    ports:
      - 6379:6379

  postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # mongo:
  #   image: mongo:6.0
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: examplepassword
  #   ports:
  #     - "27018:27017"
  #   volumes:
  #     - mongo-data:/data/db

volumes:
  mongo-data:
  postgres_data:
  grafana-storage:
